# Generated by Django 5.1.4 on 2025-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=30)),
                ('truck_description', models.TextField(null=True)),
                ('truck_price', models.FloatField()),
            ],
        ),
    ]
