# Generated by Django 5.1.4 on 2025-01-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trucks',
            new_name='Truck',
        ),
    ]
