# Generated by Django 5.1.4 on 2025-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_rename_trucks_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_image',
            field=models.ImageField(null=True, upload_to='truck_photos'),
        ),
    ]
